### ISSUE TITLE
Aggregating Data: pass a (one-item) list to groupby()

### ISSUE THREAD

**Issue by qethanm** [Datapolitan-Training/data-analysis-python#104]
The Pandas `DataFrame.grouby()` supports grouping by multiple columns.  Let's consider passing a list (syntax: `df.groupby( [ "column" ] )`) instead of a single element.

Even if you only group by a single column for now,  getting students into the habit of passing `groupby()` a list will make it easier to talk about grouping by multiple columns later.

http://training.datapolitan.com/data-analysis-python/#185

**Comment by datapolitan** [comment]
This is a great point. i don't do it so I can avoid the discussion about lists too early in the class, but it is a good practice to reinforce with them. I'm interested in what @justalfred thinks about this.

**Comment by justalfred** [comment]
I really like this idea. It's sneaky. We already gloss over the double square brackets for selecting multiple columns. This saves us potential confusion. I'll put it in.

**Comment by justalfred** [comment]
lotta `groupby`s to fix.... haha
