### ISSUE TITLE
Function Chaining: mention some drawbacks/challenges

### ISSUE THREAD

**Issue by qethanm** [Datapolitan-Training/data-analysis-python#105]
Let's mention that function chaining is good when you don't want lots of temporary variables around ... but also that it can complicate debugging (because, inevitably, you'll have to go step-by-step to find out why the end-result isn't what was expected).

At a minimum, we could "chaining to build up a data structure" from "chaining to build a plot." Students may want to try lots of different plots off that same data structure, and this will get them into the habit of saving intermediate results. 

http://training.datapolitan.com/data-analysis-python/#191

**Comment by datapolitan** [comment]
Good point. I try to reinforce these verbally but it's good to have that documented somewhere so it's clear the good and the bad.

**Comment by justalfred** [comment]
@qethanm @datapolitan my proposed solution in PR #109 .
