### ISSUE TITLE
Selecting Rows: mention Pandas query interface

### ISSUE THREAD

**Issue by qethanm** [Datapolitan-Training/data-analysis-python#106]
It's probably worth a line in this slide to mention that Pandas as other, more flexible (and more complicated) ways of selecting rows beyond plain `==` 

We could then link to the Pandas docs for the people who are curious.

http://training.datapolitan.com/data-analysis-python/#208

**Comment by datapolitan** [comment]
I like it. I still think we should anchor around a simple method they can try out, but find the right moment to invite them to explore options if they're not over-saturated with information.

**Comment by justalfred** [comment]
I went through a whole mental loop around this. But a mention makes sense. I messed up the slide numbers with my commits, so I hope this lands about where you wanted it.

**Comment by datapolitan** [comment]
That's fine and it happens @justalfred. I have starting put `name` place holders on slides to make linking easier.
