### ISSUE TITLE
Selecting rows - fuzzy matching: description of `str`

### ISSUE THREAD

**Issue by qethanm** [Datapolitan-Training/data-analysis-python#107]
Let's reword "`str` is the string object in Python" to something like "`str` holds a series of string-related functions."  

http://training.datapolitan.com/data-analysis-python/#221

**Comment by datapolitan** [comment]
Works for me. I'm sure we can figure out how to wordsmith that so it's clear

**Comment by justalfred** [comment]
I'm also going to point the link to https://pandas.pydata.org/pandas-docs/stable/user_guide/text.html

**Comment by datapolitan** [comment]
Sounds good @justalfred.
