### ISSUE TITLE
Debugging: add a note on function chaining

### ISSUE THREAD

**Issue by qethanm** [Datapolitan-Training/data-analysis-python#108]
Add a line to the effect of:

"When in doubt, break things down into smaller pieces" 

(This is especially helpful for function chaining.)

http://training.datapolitan.com/data-analysis-python/#243

**Comment by datapolitan** [comment]
I like it. Definitely reinforces best practices. I want to be really intentional in preventing this from being a blocker for people who might be apt to quit if they encounter an issue.

**Comment by justalfred** [comment]
I'm going with: "When in doubt, take a breath, try breaking things apart into smaller pieces, review the documentation, and search for help"

**Comment by datapolitan** [comment]
I like it @justalfred! Very mindful. Now we just need to find a good GIF

**Comment by justalfred** [comment]
hahah my colleagues at work are expert at finding gifs. Alas, I'm not.
