### ISSUE TITLE
Reorder A Block

### ISSUE THREAD

**Issue by datapolitan** [Datapolitan-Training/data-analysis-python#134]
As per meeting with @ebrelsford and @myarish:
 
![a_block_rev](https://user-images.githubusercontent.com/7535465/74486046-1dc31900-4e8a-11ea-8d4b-4ca20fcb9a46.jpg)

**Comment by ebrelsford** [comment]
Need a good story problem for Your Turn 1, otherwise the re-ordering is complete.
