### ISSUE TITLE
Breakdown for Co-Teaching

### ISSUE THREAD

**Issue by datapolitan** [Datapolitan-Training/data-analysis-python#42]

**Comment by datapolitan** [comment]
@juliaem How's a good way to capture this so we remember what we set? We can tag slides or put it into the README

**Comment by juliaem** [comment]
README please!

**Comment by datapolitan** [comment]
Unless @justalfred and @myarish want this, I'm pulling the explicit breakdown so you can work this out on your own between yourselves and @ebreslford or @sunwsusan
