### ISSUE TITLE
Code for hours of day

### ISSUE THREAD

**Issue by datapolitan** [Datapolitan-Training/data-analysis-python#65]
Make sure to have the code to extract hour from created date

**Comment by justalfred** [comment]
Similar to #56, is it good enough to have this in speaker notes so that we can answer questions? @datapolitan

**Comment by justalfred** [comment]
note:

```python
col = pd.to_datetime(df2['Closed Date'])
col.dt.hour
```

**Comment by datapolitan** [comment]
Definitely @justalfred. It comes up enough I want to make sure we have it, especially for new instructors like @myarish and @ebrelsford
