### ISSUE TITLE
Add release in C block aggregating

### ISSUE THREAD

**Issue by datapolitan** [Datapolitan-Training/data-analysis-python#88]

**Comment by datapolitan** [comment]
Give them a chance to play with the `groupby()` on their own.

**Comment by justalfred** [comment]
I'm less clear what this should look like. I think this fits just before the "Filtering and Sorting" section. I'm putting the "function chaining v. storing" slide just before this one. So maybe I end that slide with another bullet saying, "Try it yourself for a while"?

**Comment by datapolitan** [comment]
@justalfred There's already a "try it yourself", which is fine. This is something we can play with and see if it works.

**Comment by datapolitan** [comment]
Related to #136
