### ISSUE TITLE
Change "mistake" language in debugging

### ISSUE THREAD

**Issue by datapolitan** [Datapolitan-Training/data-analysis-python#89]

**Comment by datapolitan** [comment]
be less judgemental with language

**Comment by datapolitan** [comment]
Simple fix to be more intentional with language.

**Comment by justalfred** [comment]
I'm going with "Everyone gets errors all the time" and changing "It's just a matter of how serious they are" to "It's just a matter of how complex they are". @datapolitan, does convey the attitude you were going for?

**Comment by datapolitan** [comment]
I like it! Thanks for making the change.
