### ISSUE TITLE
Great quote for debugging slide

### ISSUE THREAD

**Issue by datapolitan** [Datapolitan-Training/data-analysis-python#98]
"Deleted code is debugged code"

**Comment by datapolitan** [comment]
Any non-trivial program contains at least one bug

**Comment by datapolitan** [comment]
Feel free to add or not. Just helps put things in context

**Comment by justalfred** [comment]
I like the quote. I'm not sure how to fit it into the story on the debugging slide. Can you help with the transition? This quote feels like a statement on what good debugging can look like, whereas the slide feels more like guiding the students on how to think about debugging.

**Comment by datapolitan** [comment]
I think that's a good point. Maybe we pull this and put it in the workbook instead.

**Comment by datapolitan** [comment]
Not doing
